version: '3.8'

services:
  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - astroid-redis:/data
    command: redis-server --save 60 1 #--loglevel warning

volumes:
  astroid-redis:
